struct stat;
struct rtcdate;

// system calls
int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int *);
int write(int, const void *, int);
int read(int, void *, int);
int close(int);
int kill(int);
int exec(char *, char **);
int open(const char *, int);
int mknod(const char *, short, short);
int unlink(const char *);
int fstat(int fd, struct stat *);
int link(const char *, const char *);
int mkdir(const char *);
int chdir(const char *);
int dup(int);
int getpid(void);
char *sbrk(int);
int sleep(int);
int uptime(void);
// int get_uncle_count(void);
int aq(void);
// int rel(void);
// uint lifetime(void);
// int set_bjf_for_process(int pid, float priority_ratio, float arrival_time_ratio, float executed_cycle_ratio, float process_size_ratio);
// int set_bjf_for_all(float priority_ratio, float arrival_time_ratio, float executed_cycle_ratio, float process_size_ratio);
// int change_queue(int pid, int queu);
// int ps(void);
int print_num_syscalls(void);
void *open_sharedmem(int);
int close_sharedmem(int);

// ulib.c
int stat(const char *, struct stat *);
char *strcpy(char *, const char *);
void *memmove(void *, const void *, int);
char *strchr(const char *, char c);
int strcmp(const char *, const char *);
void printf(int, const char *, ...);
char *gets(char *, int max);
uint strlen(const char *);
void *memset(void *, int, uint);
void *malloc(uint);
void free(void *);
int atoi(const char *);
